### ISSUE TITLE
Possible scaling issues

### ISSUE THREAD

**Issue by Apollinaire** [StateOfJS/StateOfJS-Vulcan#10]
I get long loading times on changing steps (between 1s and 30s). I started the survey this morning and did not experience this kind of latency. Currently it's 4:50 PM CET.
I also got a few 502 / 503s http errors on graphql queries 'response' and 'updateResponse', that were caught by the alert saying "You have unsaved data! Please choose "Cancel", then save by using the previous/next buttons at the bottom of the page."

**Comment by SachaG** [comment]
I scaled the containers up, it should be better now. Thanks for letting me know :)
