### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [StateOfJS/StateOfJS-Vulcan#12]
First off it takes forever to load, secondly when I enter a password (which, is kind of weird and offputting to be honest, not sure why you can't find any other way to ensure there's no gaming if that's the purpose) it just sits there seemingly with no reaction at all.

**Comment by SachaG** [comment]
Sorry to hear that, we were having some server issues a while back. Could you try again now?

**Comment by WhatFreshHellIsThis** [comment]
Ok, thank you.  I'm not going to participate anymore in this survey as I now have privacy concerns about it.
