### ISSUE TITLE
What is the source of the Front-end Frameworks > Other Options suggestion field?

### ISSUE THREAD

**Issue by petermuessig** [StateOfJS/StateOfJS-Vulcan#125]
I want to select the Front-end Framework [`OpenUI5`](https://bestofjs.org/projects/openui5) in the `Other Options` suggestion field, which is not available as suggestion. For the `State of JS 2020` survey I asked and the recommendation was to add it to [bestofjs.org](https://bestofjs.org) if I want to be able to select it. Is there anything missing? Thanks...

**Comment by SachaG** [comment]
Yes Best of JS is still the source. It's weird if it's not showing up in the survey…

**Comment by SachaG** [comment]
Oh ok, I see what happened… I updated the `yaml` file that lists the projects but forgot to convert it to json, which is what is actually imported… I'll update the app now.

**Comment by petermuessig** [comment]
Now it works, thanks @SachaG for your fast reaction!

**Comment by SachaG** [comment]
Great, so sorry about this issue!
