### ISSUE TITLE
survey design flaw - gerrymandering

### ISSUE THREAD

**Issue by Maxhodges** [StateOfJS/StateOfJS-Vulcan#126]
This question structure is poorly designed.  Certain ranking outcomes are prohibited based on the initial pairings.

So if I think **Managing Dependencies** is more of a problem than **Async Code**, so I select it, but I think **Async Code** is more of a problem than both **Code Architecture** and **Writing Modules** you wouldn't be able to know that.

![image](https://user-images.githubusercontent.com/957271/150709054-c657f4e2-1aaf-4cb0-b420-8dc1ab81fde4.png)

**Comment by SachaG** [comment]
I think in aggregate that gets smoothed out since everybody gets different start pairings.
