### ISSUE TITLE
I18n values are shown instead of actual values

### ISSUE THREAD

**Issue by jonybar9** [StateOfJS/StateOfJS-Vulcan#128]
In most of the questions, the title is the I18n attribute and not the actual value.
This one is from the Language section but it goes on.

![image](https://user-images.githubusercontent.com/44051582/150786413-5585b10e-e0ac-4474-b791-59b24f038356.png)

**Comment by SachaG** [comment]
Sorry about that, I think it was an API issue. Should be better now.
