### ISSUE TITLE
Weird Labels

### ISSUE THREAD

**Issue by PickleNik** [StateOfJS/StateOfJS-Vulcan#130]
<img width="432" alt="Screen Shot 2022-01-24 at 9 22 30 AM" src="https://user-images.githubusercontent.com/31113245/150800417-80a3a404-af8d-4c18-8a00-cb60620c748b.png">
<img width="424" alt="Screen Shot 2022-01-24 at 9 29 20 AM" src="https://user-images.githubusercontent.com/31113245/150801673-45af53d3-2056-4878-b0f8-7236083fd066.png">

About half the labels appear like this for me. I was confused by this and though I didn't know what that is although I did. Tried in Chrome, FF, Safari (also tried the Incognito mode without extensions, all browsers are of latest version atm.)

**Comment by SachaG** [comment]
Sorry about that, I think it was an API issue. Should be better now.
