### ISSUE TITLE
clarify meaning of answer options

### ISSUE THREAD

**Issue by diminutivesloop** [StateOfJS/StateOfJS-Vulcan#132]
Some of the answer options are ambiguous and would benefit from clarification up-front so everyone completing the survey has a shared understanding of what they mean. Specifically it's not clear what it means to have "used" a technology or "know what it is". I work on projects that use build tools like rollup, but I'm not sure it makes sense to say I've used those tools since I wasn't responsible for setting the project up and have made at most limited changes to the config. And in some cases my only usage of a technology has been indirectly through another tool that uses it as a dependency (such as Webpack via the Angular CLI). As for knowing what a technology is I find that I've heard about many of the technologies on the survey so I can't say I've "never heard of" them, but I often don't remember enough details to confidently say I "know what it is" either.

**Comment by SachaG** [comment]
Those are fair points but changing the wording at this point would make it tricky to compare results with historical data, as we wouldn't know if any change is due to actual trends or just the wording change. So it's probably going to stay the same for now, sorry…
