### ISSUE TITLE
Weird back-end frameworks list

### ISSUE THREAD

**Issue by HZooly** [StateOfJS/StateOfJS-Vulcan#14]
I am not sure if I should write an issue here for that, but I am a little bit surprised to find tools like Nuxt, Next and Gatsby in the back-end frameworks list, don't you?

**Comment by SachaG** [comment]
I can see where you're coming from, but we wanted to include those somewhere and that still seemed like the most appropriate place.

**Comment by HZooly** [comment]
I understand your choice, it makes the survey shorter 😄

**Comment by MarkPieszak** [comment]
I agree with @HZooly here.

Next/Nuxt/Gatsby are more middle-end universal rendering and not backend API frameworks such as Express/koa/hapi (or anything in the typical Node.js family).

Here is Rauch the creator of Next.js talking about it specifically: https://github.com/zeit/next.js/issues/239#issuecomment-260084989

I hope some changes can be made to the survey, these should be in a static rendering / universal rendering section of their own (along with many other options). @SachaG

**Comment by SachaG** [comment]
Well, the goal is not just to add as many frameworks and categories as we can, there's a balance to be found. 

In any case down the line we may end up doing a separate survey for Node and JS on the back-end more generally, so that will take care of this issue :)
