### ISSUE TITLE
"Continue with account" doesn't work

### ISSUE THREAD

**Issue by ghost** [StateOfJS/StateOfJS-Vulcan#152]
I type my email in Create Account form https://survey.devographics.com/survey/state-of-css/2022 and click the button "Continue with account". I see a "Check your inbox! ..." message but I don't receive any email.

**Comment by SachaG** [comment]
I just tried it and it worked for me. Maybe check your spam folder, or else try again?

**Comment by ghost** [comment]
Yes, 5 emails with the login link in the spam folder( Thanks!
