### ISSUE TITLE
Bug with "Leave a comment" button (Safari)

### ISSUE THREAD

**Issue by germanfrelo** [StateOfJS/StateOfJS-Vulcan#154]
The "Leave a comment" section/button of every form section/question is buggy on Safari. On every click on the button, its size is increased as well as the space around, and its position is changed.

- O.S.: macOS Monterey 12.6
- Browser: **Safari 16.0**

Video:

https://user-images.githubusercontent.com/14282156/195403135-2180ed56-3ab9-45b6-9cf2-fc7b9e3d9bae.mp4

**Comment by SachaG** [comment]
Thanks for the video! I'll track this issue over here: https://github.com/Devographics/Monorepo/issues/126

So I'll close this one for now.
