### ISSUE TITLE
No Framework option missing

### ISSUE THREAD

**Issue by bengfarrell** [StateOfJS/StateOfJS-Vulcan#16]
I really thought the State of JS 2017 was very telling. No Framework JS was second in the frameworks listing only behind React. I'm sure it's dropped, but I can't imagine so significantly that its insignificant now. I'd really like to see those results

**Comment by SachaG** [comment]
That's true… but we had to make some cuts to avoid the survey getting longer and longer every year as we add new options, sorry!
