### ISSUE TITLE
Survey doesn't save from the Flavors of JS section onwards.

### ISSUE THREAD

**Issue by idmadj** [StateOfJS/StateOfJS-Vulcan#2]
After selecting answers on the Flavors of Javascript section, clicking the next button pops a dialog informing that the answers are not saved. Clicking OK navigates to the next section. Clicking the Previous button in the new section pops the same dialog, then clicking OK navigates back to the previous section, where all answers are unanswered. Answers in previous sections are correctly saved.

This is on the Gmail browser on Android 10.

**Comment by SachaG** [comment]
Weird, I haven't noticed this. Are you still encountering this issue? Are you able to try from another device?

**Comment by Abubabubi** [comment]
Same thing happens for me, I'm being prompted to use previous/next buttons on the bottom of the page, but I'm already using them.

**Comment by SachaG** [comment]
@Abubabubi are you also on Android 10 with the Gmail browser?

**Comment by Abubabubi** [comment]
Nope, Mac chrome

**Comment by idmadj** [comment]
I was able to complete the survey by opening in Chrome (same device).

Now opening the site returns "503 Service Unavailable: No healthy endpoints to handle the request. If you're the owner of this app, see this article for more information: http://bit.ly/2uCFzOo"

**Comment by idmadj** [comment]
Just gave it another try and I was able to navigate through all section after selecting different answers, from both Gmail browser and Chrome.
