### ISSUE TITLE
Hapi.js framework missing

### ISSUE THREAD

**Issue by timcosta-tempus** [StateOfJS/StateOfJS-Vulcan#20]
Hey all -

One of the more popular Node.js frameworks, [hapi.js](https://hapi.dev/) is missing from the survey. I'd love to fill it out, but my data would be misleading without inclusion of the Hapi framework.

**Comment by devinivy** [comment]
I am in the same boat.  By downloads it is more widely used than some of the items in the current survey (e.g. feathers and sails), which may also support it being included.

**Comment by SachaG** [comment]
Sorry about that, we'll correct that next year.
