### ISSUE TITLE
Requires login

### ISSUE THREAD

**Issue by olpeh** [StateOfJS/StateOfJS-Vulcan#22]
https://survey.stateofjs.com/ says:

>Please log in or sign up to begin.

Expected behaviour: 
Answer the survey

**Comment by SachaG** [comment]
Oh wow, I can't believe I overlooked that bug! I guess I must have accidentally coded a log in form, set up a user account system, and written an explanation of why we now ask for accounts in our privacy policy! Such a dumb mistake on my part, PR welcome.
