### ISSUE TITLE
Multiple response questions are considered unanswered when no answer applies

### ISSUE THREAD

**Issue by DamianoMagrini** [StateOfJS/StateOfJS-Vulcan#23]
As stated in the title, if no answer is correct in a multiple response question, the only option is to leave it blank. This, however, makes the question appear (and count as) unanswered. While this behavior is logical, a "none" or "does not apply" answer could be added as well, since it would allow people for whom no answers are correct to count in the results.

I, for instance, don't use any "utility" ("Other Tools" section, first question), and so I had no choice but to leave the question blank, and hence "unanswered".

**Comment by SachaG** [comment]
I get your point but the completion percentages are provided more as indication so you can remember where you left off, you don't need to get everything to 100% necessarily. So leaving questions unchecked is fine :)

**Comment by DamianoMagrini** [comment]
Sure, I understand. Though I fear I may not have explained what I mean clearly, so I'll try with an example. Let's consider the "utilities" question, and, for simplicity, let's say two people take the survey. Person A uses lodash, and selects it, person B doesn't use any utility and so leaves the question blank. While they surely can both submit the survey, the final results will show that 100% of the people use lodash (which is not true), as person B's blank answer was not considered.

Or am I just getting something wrong about how the results are calculated?

**Comment by SachaG** [comment]
We don't use percentages for these questions so I don't think that issue would happen.
