### ISSUE TITLE
How are you storing my email and password?

### ISSUE THREAD

**Issue by Supuhstar** [StateOfJS/StateOfJS-Vulcan#24]
Are they stored alongside the answers I gave? Are they encrypted or hashed? If so with what scheme? What is your plan of a data breach leaks these?

**Comment by cryptoquick** [comment]
This is a Meteor app, so it uses the popular accounts-password package.

It first gets the password data here:
https://github.com/StateOfJS/StateOfJS-Vulcan/blob/987d89fa783f54e6242bb485c182bc057fc50b65/packages/vulcan-accounts/imports/ui/components/LoginFormInner.jsx#L858

Keep in mind, this is a React JSX file, and so this code is executed on the frontend. Consider that however you may.

You'll find the hash algorithm called here (SHA-256):
https://github.com/meteor/meteor/blob/a1caff04b7ff1f0803266af7b6f305f354b9b977/packages/accounts-password/password_client.js#L75

**Comment by SachaG** [comment]
@cryptoquick thanks for providing a detailed answer!

@Supuhstar while I can certainly appreciate your concerns for privacy and security I find your tone a bit disingenuous. What sort of "plan" am I supposed to have in case of a data breach? We're just a few people doing this as a side project, not Equifax or Sony. 

If your questions were genuine then sorry for making assumptions, but if you don't want to trust us with an email/password combination then that's entirely fine as well.
