### ISSUE TITLE
What does "your country" mean?

### ISSUE THREAD

**Issue by MichalBryxi** [StateOfJS/StateOfJS-Vulcan#25]
I think this one is a bit ambiguous. Not sure what are you asking about?

Are you asking about mu country of origin? What my nationality is? Which passport(s) do I own? What are my citizenship(s)? Where do I currently live? There are quite a few options I can choose right now, depending on what are you asking for.

<img width="799" alt="Screenshot 2019-12-01 at 16 40 42" src="https://user-images.githubusercontent.com/847473/69916281-7e30e580-1459-11ea-8d76-e14aa15b7ab8.png">

**Comment by SachaG** [comment]
I'll add some clarification, thanks.
