### ISSUE TITLE
Clarification of who is in the State of JavaScript team

### ISSUE THREAD

**Issue by felnne** [StateOfJS/StateOfJS-Vulcan#27]
Hi,

I have a hopefully simple question regarding your [privacy policy](https://github.com/orgs/StateOfJS/people), specifically this section:

> Who will have access to my data? Will any third parties see my data?
>
> The State of JavaScript team will have access to the full dataset including emails. The anonymized dataset (without emails) will be made public. No third party will be given access to the non-anonymized data.

Is there anything that explains who is in that team? I assume 'State of JavaScript' isn't a company etc. and instead relates to the parent GitHub [organisation](https://github.com/StateOfJS) of this project?

If so, is the membership of that organisation complete or are there other volunteers etc. that are included? Only it currently only has one member.

If there's any clarification you could provide it would be greatly appreciated.

Thanks

**Comment by SachaG** [comment]
Good point! I'll add a link to the org and make its members public.
