### ISSUE TITLE
Email required warning

### ISSUE THREAD

**Issue by jllagerberg** [StateOfJS/StateOfJS-Vulcan#5]
Whenever I try to log in or reset password I get a `Email required` warning.

![Untitled](https://user-images.githubusercontent.com/27690759/69611216-99e95580-102d-11ea-8e89-7dd1c0012a83.jpg)

**Comment by SachaG** [comment]
What browser are you using? Also is your email really entered in the field, it looks a bit greyed out in the screenshot? But maybe that's just a visual thing.

**Comment by jllagerberg** [comment]
Now it suddenly works :)
