### ISSUE TITLE
Missing option for Indians / South Asians in the Ethnicity question

### ISSUE THREAD

**Issue by ashmenon** [StateOfJS/StateOfJS-Vulcan#53]
Hi guys, am I missing something or is there not really an option for Indians / South Asians in the ethnicity question? I know it's an optional question but I would assume *Indians* would be in there, considering how heavily we're represented in IT 😂 

![image](https://user-images.githubusercontent.com/2948776/96454466-78e5b080-124e-11eb-9c9e-580435305ca4.png)

**Comment by SachaG** [comment]
Oh you're totally right, somehow South Asian got dropped from the options! I'll fix it right away, sorry about that :(

**Comment by ashmenon** [comment]
@SachaG not a problem, and thank you for looking into it! ❤️
