### ISSUE TITLE
Can't register with a .com.au email address

### ISSUE THREAD

**Issue by dwightwatson** [StateOfJS/StateOfJS-Vulcan#57]
I tried to register with my Australian email address, but nothing was happening - no error message, nothing.

I eventually tried dropping the `.au` and it suddenly let me register.

Is there a validation issue that's incorrectly validating Australian emails and also not presenting the error to the user?

**Comment by SachaG** [comment]
I'm not aware of such a validation so maybe it's a coincidence? Maybe the server was slow to respond or errored out the first time?

**Comment by dwightwatson** [comment]
Maybe, I did try a number of times in two browsers. And it worked the instant I removed the `.au` which made me suspect it was something internal. I'll close this for now, thanks for getting back to me.
