### ISSUE TITLE
Taiwan is not a country

### ISSUE THREAD

**Issue by otakustay** [StateOfJS/StateOfJS-Vulcan#68]
![image](https://user-images.githubusercontent.com/639549/97280875-c9c15e80-1877-11eb-809f-ee36744cd095.png)

**Comment by hefangshi** [comment]
Taiwan is not a country+1

**Comment by gluo1130** [comment]
Taiwan is not a country+1

**Comment by akirarika** [comment]
Taiwan is not a country+1

**Comment by buhichan** [comment]
乳滑了乳滑了(无关心

**Comment by Vicfeel** [comment]
Taiwan is not a country+1

**Comment by SyMind** [comment]
Taiwan a part of China.

**Comment by Janlay884181317** [comment]
Taiwan a part of China.

**Comment by otakustay** [comment]
Also I noticed Hong Kong and Macau are listed there, if you are willing to include all these regions, a title like "Country or region" is a more appropriate one.

**Comment by tuluffy** [comment]
![image](https://user-images.githubusercontent.com/26808339/97281553-a0ed9900-1878-11eb-83c8-159fd84dad42.png)

**Comment by bluestrings** [comment]
Taiwan is not a country+1

**Comment by hitao123** [comment]
Taiwan a part of China.

**Comment by Junior2Ran** [comment]
As everyone knows, Taiwan HongKong and Macau are part of China since ancient times. It's a common sense.

**Comment by magicianShiro** [comment]
Taiwan a part of China.

**Comment by zheng-chuang** [comment]
Taiwan is not a country+1

**Comment by SachaG** [comment]
I agree "Country or Region" would be a better name for that field. 

But maybe I should also add a trigger warning before the question, such as "Warning: Geographical Content". Clearly some people are deeply troubled whenever they see the "T-word", and I can only apologize for causing such anguish and pain.

**Comment by SachaG** [comment]
<img width="714" alt="Screen Shot 2020-10-27 at 19 50 59" src="https://user-images.githubusercontent.com/358832/97291829-c507a500-188d-11eb-9770-b4a48fbc63f4.png">

Hopefully we can all live in peace now :)
