### ISSUE TITLE
Error: Could not find survey response document

### ISSUE THREAD

**Issue by bungu** [StateOfJS/StateOfJS-Vulcan#85]
After answering some questions, I got 503 error and soon after reloading I got this message:

> Could not find survey response document. Please reload, or if that doesn’t work leave an issue.

So I'm leaving an issue :) Not sure if i could provide any more useful information.

My survey url: https://survey.stateofjs.com/survey/state-of-js/2020/yfYow3HFBj954veLG

**Comment by bungu** [comment]
Now everything works fine. I guess heavy traffic caused the issue.

**Comment by SachaG** [comment]
Yes, sorry about that! I scaled up our servers and it should work now.

**Comment by gwildu** [comment]
Seems to happen again, my data seems to be all lost after reloading :(
