### ISSUE TITLE
Link to leave issue/suggestion doenst work

### ISSUE THREAD

**Issue by evsasse** [StateOfJS/StateOfJS-Vulcan#86]
When clicking the "leave a suggestion" link on the footer, it goes to https://survey.stateofjs.com/survey/state-of-js/2020/yeZtQSdArE2K5hwdX/$https://github.com/StateOfJS/StateOfJS-Vulcan/issues (404). Instead of https://github.com/StateOfJS/StateOfJS-Vulcan/issues.

<img width="1230" alt="Screen Shot 2020-12-09 at 07 53 34" src="https://user-images.githubusercontent.com/7394653/101621201-35105b80-39f4-11eb-8857-41f60b7240cc.png">

**Comment by SachaG** [comment]
Thanks! This is the same issue as https://github.com/StateOfJS/StateOfJS-Vulcan/issues/76 so I'll close this one for now.
