### ISSUE TITLE
Web Test Runner can not be selected even though it's on best of js?

### ISSUE THREAD

**Issue by daKmoR** [StateOfJS/StateOfJS-Vulcan#87]
This is a follow up of https://github.com/StateOfJS/StateOfJS-Vulcan/pull/80

Fill in `Web T` should allow selecting `Web Test Runner` but you get `No matches found`

![Screenshot 2020-12-09 at 12 18 49](https://user-images.githubusercontent.com/24378/101623556-eb863780-3a18-11eb-992b-20b062f6601b.png)

For reference, it's available on https://bestofjs.org/projects/web-test-runner
![Screenshot 2020-12-09 at 12 19 21](https://user-images.githubusercontent.com/24378/101623646-0bb5f680-3a19-11eb-9d2d-6c9673419fa7.png)

PS: I also tried variations like web-test-runner, @web/test-runner, web test, ... - but no luck

**Comment by SachaG** [comment]
I need to update a JSON and redeploy before it can show up, but I don't know if I'll have a chance to do it for the 2020 survey, sorry…

**Comment by daKmoR** [comment]
oh no 😭

any way I could help make it happen? or is there no chance? 😅

**Comment by SachaG** [comment]
Sorry, I'd rather not redeploy while we're receiving a lot of traffic in case I break anything. Apologies, I'll make sure the project is selectable for the next survey.

**Comment by daKmoR** [comment]
fair enough - thx for the info 🤗
