### ISSUE TITLE
Survey Translation

### ISSUE THREAD

**Issue by marceloemanoel** [StateOfJS/StateOfJS-Vulcan#9]
Hey everyone! 

Are you interested in translating the survey into other languages? 
I could help to translate it into Brazilian Portuguese.

Keep up the good work!

**Comment by SachaG** [comment]
Thanks for volunteering! We didn't have time to translate the actual survey this time, but we'll try to get the results site translated at least. I created a new thread to centralize info about that: https://github.com/StateOfJS/State-of-JS-2019/issues/8
