### ISSUE TITLE
Being able to be less opinionated 

### ISSUE THREAD

**Issue by ArnaudBarre** [StateOfJS/StateOfJS-Vulcan#91]
TDLR: I would like to have the option: Heard of it, no strong opinion on it

There is a lot of technologies that I've heard off, but I'm still unsure if I ever use it or not. 

I'm currently using React as main framework, and I know that I would never use Angular again. But Vue, I've tried it, learnt the basics, it's cool. But I can't say I will never use it again, or I'm not interested. I'm just happy that a different option exists and maybe interesting in the future or for others projects. And for svelte, I know what it is, I can say I want to learn it because it's impossible to learn every cool JS stuff.

Kind of related: you can't unselect an option and go back to no answer. So once you click on something you know, you need to choose either you like or not. 

For most builds tools (esbuild, swc), the correct answer will more be: heard of it, not _currently_ using it. (I may learn or may not, I don't know yet)

"I don't have an opinion" is something that the JS community needs more.

**Comment by SachaG** [comment]
I think broadly speaking you're right, but when it comes to the survey specifically I do think forcing people to commit to a interested/not interested choice makes for more interesting results. If we had a "not sure/no opinion" option I expect most people would pick that and the results would become far less meaningful. 

There's also the more practical matter that keeping the same five options lets us do historical comparisons to highlight trends over time, so I don't see us changing these options anytime soon, sorry.

**Comment by SachaG** [comment]
Good point about not being able to "unanswer" a question though, ideally that would be possible although radio buttons typically don't let you do that on the web at least.
